# una hora con la zona de tiempo. Mira el Server.hs
scalar Zoned

type Query {
  # Obtener una lista de unidades disponibles (estan viajando ahora)
  # Obtener una lista de unidades que hayan estado dentro de una alcaldía
  # Consultar los el historial de ubicaciones/fechas de una unidad dado su ID
  ubicaciones(unidadId: Int, alcaldia: String, horaIso8601: Zoned): [UnidadHoraUbicacion!]!

  # Obtener una lista de alcaldías disponibles
  # (alcaldias donde viajan metrobuses)
  # filtrado de la hora en el parametro
  alcaldiasDisponibles(aHoraIso8601: Zoned): [String!]!
}

type UnidadHoraUbicacion {
  uHora: Zoned!
  uAlcaldia: String!
  uLatLonText: String!
  uEwkbB64: String!
  uVehicleId: Int!
}
