apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: arkon-webserver
spec:
  selector:
    matchLabels:
      app: arkon-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: arkon-webserver
    spec:
      containers:
      - name: arkon-webserver
        image: ysangkok/arkon-webserver@sha256:e56a946c0920994fc09f9891f4676a195f51e5ce098da93ac0490b06a891634a
        args: ["postgres-demo-0"]
        ports:
        - containerPort: 3000
